### ISSUE TITLE
I suppose SectorC could win from the 'Assembly' entry.

### ISSUE THREAD

**Issue by HenkPoley** [MichalStrehovsky/sizegame#20]
For various definitions of winning, probably disqualified because it doesn't run under an OS.

SectorC is a C compiler in a boot sector: 

* https://xorvoid.com/sectorc.html
* https://github.com/xorvoid/sectorc

**Comment by MichalStrehovsky** [comment]
Yeah, this repo measures hello worlds. It would be ~20 bytes for a bootsector hello world, but I only measure x64 Windows.
