### ISSUE TITLE
Differnt C compiler

### ISSUE THREAD

**Issue by gtworek** [MichalStrehovsky/sizegame#34]
Hello!
With Tiny C Compiler, a fully working exe meeting your criteria is 2KB. See https://x.com/0gtweet/status/1829109399861825970

**Comment by MichalStrehovsky** [comment]
I know about it. It's also not a first choice for pretty much anyone when shipping on windows. See https://github.com/MichalStrehovsky/sizegame/issues/14#issuecomment-1556152526

**Comment by gtworek** [comment]
I see. Thanks anyway :)
