### ISSUE TITLE
Update Go executable file size

### ISSUE THREAD

**Issue by vkusnyjchaj** [MichalStrehovsky/sizegame#35]
I refer to rules:

- If the compiler has a master switch "enable optimizations", that switch should be used.
- You can set the optimization preference to size optimizations, provided they don't change semantics

to request reevaluation of Go executable file size.

I refer to [Go official docs](https://go.dev/doc/faq#Why_is_my_trivial_program_such_a_large_binary) to request compilation using optimization flags:
`go build -ldflags="-s -w" -o helloworld.exe helloworld.go`

- Flags -ldflags are special options passed to the Go linker ( ld ) during the build process. These flags can modify the behavior of the linker and influence how the final executable is generated
- Flag -w Omit the DWARF symbol table
- Flag -s Omit the symbol table and debug information
- Flag -o Write output to file
[Flags info](https://pkg.go.dev/cmd/link)

**Comment by MichalStrehovsky** [comment]
Do backtraces still work if you pass these arguments? https://www.dolthub.com/blog/2023-11-10-stack-traces-in-go/

If they change, this would be against rules because it's semantics-changing.

**Comment by MichalStrehovsky** [comment]
Go is not the only language that needs to pay for stack traces. But it is what it is - the stack traces are possibly also one of the reasons why people choose Go. Things are not free and this benchmark simply measures the costs of defaults, not whatever size is possible to achieve.

Thanks for bringing this up!
